version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: webuser
      POSTGRES_PASSWORD: webpass
      POSTGRES_DB: web
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      PORT: "8000"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://webuser:webpass@db/web"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
